# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/FRC2023',
                'doc_host': 'https://WHEARobotics.github.io',
                'git_url': 'https://github.com/WHEARobotics/FRC2023',
                'lib_path': 'FRC2023'},
  'syms': {'FRC2023.core': {'FRC2023.core.foo': ('core.html#foo', 'FRC2023/core.py')}}}
